### ISSUE TITLE
Cheat Sheets (Controller): Add global ignores

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3044]
We recently merged #2777 - which added the 'ignore' attribute to triggers. This allows use to specify that for a particular set of trigger words (for example `phrases`), there are some associated words that can be ignored (for example, `english to` and `basic`); this allows us to do things like `basic english to X phrases` to trigger the cheat sheet.

The downside to this is that it does not allow us to do `basic english to X cheat sheet`; thus the idea of 'global' ignores.

A 'global' ignore would be a phrase, that should be ignored _regardless_ of the trigger, as long as a cheat sheet has the correct category assigned.

The syntax should probably look something like:

``` yaml
language:
  startend:
    - "phrases"
    - "translations"
  ignore: # Standard ignores, only apply to the triggers from this category ("phrases" and "translations")
    - "basic"
  global_ignore: # Global ignores, apply to any trigger. 
    - "english to"
    - "language"
```

@zachthompson Do you believe the use case for this is strong enough to warrant the implementation? It would be nice to be able to do things like `haskell syntax cheat sheet` as opposed to just `haskell syntax`; though I'm not sure how much of the existing 'ignore' infrastructure we'd have to re-implement in order to get this to work.

/cc @moollaza @duckduckgo/community-leaders 

---

IA Page:  http://duck.co/ia/view/cheat_sheets 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zachthompson

**Comment by zachthompson** [comment]
I don't think we have a big enough need to worry about this atm.

**Comment by GuiltyDolphin** [comment]
Hmm, @zachthompson; something similar to this (though not exactly the same) might be more immediately useful for something like #1528 - where it may be useful to apply some `ignore` phrases to *every* category rather than each individually.

For example:

```yaml
global:
  ignore:
    - "for"
```

To add `for` to each `ignore`; allowing queries like `links for X`, `cheat sheet for X`, `cheat codes for X` etc.
