### ISSUE TITLE
Json Validator: Implement design tweaks

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#3474]
There are some minor design changes that should be made:

### CSS
- `<textarea>` should have `monospace` font family -- remove quotes around `'monospace'` in CSS
- Only enable validate button once the `<textarea>` has content
- Add `whole` class to `<textarea>` and `<pre>`
- Use proper CSS comment syntax `/* */` for `overflow: auto`

Should look like:

```css
.zci--json_validator .json_validator--input {
    margin-bottom: 1.5em;
    font-family: monospace;
    overflow: auto;  /* Hide default scrollbars on IE */
}

.zci--json_validator button {
    cursor: default;
}

.zci--json_validator .json_validator--result__wrap {
    margin-top: 1em;
}

/* Mobile */
.is-mobile .zci--json_validator button {
    text-align: center;
    padding-left: 0;
    padding-right: 0;
}

.is-mobile .zci--json_validator textarea {
    resize: vertical;
}
```

### HTML
- Remove "gw" wraps from `<textarea>`, `<btn>` and `<pre>` --- these are only necessary when we have multiple columns in a `<gw>` element
- set `tx--12` font size for result
- add `Results` heading to output

Should look like: 

```html
<textarea name="json_validator--input" class="json_validator--input whole tx--12 frm__text" rows="{{cols}}" cols="60" placeholder="Paste code here..."></textarea>

<button class="btn btn--skeleton whole--screen-s" disabled>Loading..</button>

<div class='json_validator--result__wrap is-hidden'>
    <h6 class="text--secondary">Results:</h6>
    <pre class="json_validator--result whole tx--13"></pre>
</div>
```

### JS
- Do not remove `c-base` class from container -- this is not necessary
- update to match adjusted HTML
- change `cols` to `rows` -- that was a typo I made on the last PR...

### Result:

<img width="918" alt="json_validator_at_duckduckgo" src="https://cloud.githubusercontent.com/assets/873785/17341493/d846de5e-58c2-11e6-9ace-0e33dc8580d7.png">

<img width="1063" alt="json_validator_at_duckduckgo" src="https://cloud.githubusercontent.com/assets/873785/17341501/e3c5a256-58c2-11e6-85a9-3149a29f4dd0.png">

The current design is OK, but I'm sure we can make this better for V2.

------
IA Page:  http://duck.co/ia/view/json_validator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305
