### ISSUE TITLE
Crontab Cheatsheet: Bottom text is getting cut-off 

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#946]
![screen shot 2015-01-21 at 2 51 51 pm](https://cloud.githubusercontent.com/assets/81969/5843805/22e77fc6-a17d-11e4-9199-3ac4c238acb5.png)
https://duck.co/ia/view/crontab_cheat_sheet

**Comment by MrChrisW** [comment]
This is by design, [see CSS lines](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/crontab_cheat_sheet/crontab_cheat_sheet.html#L3-L4)

Easy solution is to adjust the `max-height` value, however text can still be cut off if the window is resized:

![cron](https://cloud.githubusercontent.com/assets/5282264/5848531/62ca0b80-a214-11e4-8e50-0f0f8aa72c7a.png)

**Comment by altern8tif** [comment]
Just thinking if this cheat sheet should be ported to JSON instead...

**Comment by nickcolley** [comment]
How about adding a subtle gradient?

```html
<div class="crontab-container">
    <div class="crontab-column"></div>
    <div class="crontab-column"></div>
</div>
<div class="crontab-container-overlay"></div>
```

```css
.crontab-container-overlay {
    position: relative;
    margin-top: -1em;
    height: 1em;
    background-image: linear-gradient(transparent, #F2F2F2);
}
```

![image](https://cloud.githubusercontent.com/assets/2445413/11883161/d94d99c8-a508-11e5-989a-47a5bb22a0a2.png)
